# ECWoC’26 Smart Label Config
bug:
  - 'bug'
  - 'error'
  - 'crash'
  - 'issue'
  - 'fail'

frontend:
  - 'html'
  - 'css'
  - 'ui'
  - 'tailwind'
  - 'react'
  - 'design'

backend:
  - 'api'
  - 'server'
  - 'node'
  - 'express'
  - 'database'
  - 'db'

documentation:
  - 'readme'
  - 'docs'
  - 'documentation'
  - 'guide'
  - 'tutorial'

enhancement:
  - 'feature'
  - 'improvement'
  - 'upgrade'
  - 'new functionality'

question:
  - 'question'
  - 'help'
  - 'clarify'
  - 'support'
